MVIT:
  DROPPATH_RATE: 0.1
  DEPTH: 10
  PATCH_KERNEL: [1, 7, 7]
  PATCH_STRIDE: [1, 4, 4]
  PATCH_PADDING: [1, 3, 3]
  DIM_MUL: [[1, 2.0], [3, 2.0], [8, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [8, 2.0]]
  POOL_KVQ_KERNEL: [1, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 4, 4]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1]]
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.00025
  LR_POLICY: cosine
  MAX_EPOCH: 305
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  CLIP_GRAD_L2NORM: 1.0

